- type: gameMapPool
  id: DefaultMapPool
  maps:
# DeltaV
  - Arena
  - Asterisk
  - Chibi
  - Edge
  - Glacier
  - Hammurabi
  - Lighthouse
  - Micro
  - Pebble
  - Shoukou
  - Tortuga
  - TheHive
  - Submarine

# Nyano
  - Glacier

# Offs
  - Atlas
  - Bagel
  - Box
  - Cluster
  - Core
  - Fland
  - Marathon
  - Meta
  - Oasis
  - Omega
  - Origin
  - Saltern
  - Packed
  - Reach
  - Train

# Corvax
  - CorvaxDelta
  - CorvaxAvrite
  - CorvaxSilly
  - CorvaxOutpost
  - CorvaxAstra
  - CorvaxGelta
  - CorvaxMaus
  - CorvaxIshimura
  - CorvaxPaper
  - CorvaxPilgrim
  - CorvaxTerra
  - CorvaxFrame
