- type: antag
  id: Nukeops
  name: roles-antag-nuclear-operative-name
  antagonist: true
  setPreference: true
  objective: roles-antag-nuclear-operative-objective
  guides: [ NuclearOperatives ]
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 7200 # DeltaV - 2 hours
  - !type:DepartmentTimeRequirement # DeltaV - Security dept time requirement
    department: Security
    time: 3600 # DeltaV - 1 hours

- type: antag
  id: NukeopsMedic
  name: roles-antag-nuclear-operative-agent-name
  antagonist: true
  setPreference: true
  objective: roles-antag-nuclear-operative-agent-objective
  guides: [ NuclearOperatives ]
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 7200 # DeltaV - 2 hours
  - !type:DepartmentTimeRequirement # DeltaV - Medical dept time requirement
    department: Medical
    time: 3600 # DeltaV - 1 hours

- type: antag
  id: NukeopsCommander
  name: roles-antag-nuclear-operative-commander-name
  antagonist: true
  setPreference: true
  objective: roles-antag-nuclear-operative-commander-objective
  guides: [ NuclearOperatives ]
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 7200 # DeltaV - 2 hours
  - !type:DepartmentTimeRequirement # DeltaV - Security dept time requirement
    department: Security
    time: 3600 # DeltaV - 1 hours
