name: CRLF Check

on:
  push:
    branches: [ cursed, tests-with-reagents ]
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]

jobs:
  build:
    name: CRLF Check
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.6.0
    - name: Check for CRLF
      run: Tools/check_crlf.py
